// <auto-generated />
using System;
using GunplaridiseSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GunplaridiseSite.Migrations
{
    [DbContext(typeof(GunplaridiseContext))]
    partial class GunplaridiseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("GunplaridiseSite.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("GunplaridiseSite.Models.Gunpla", b =>
                {
                    b.Property<int>("GunplaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GradeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GunplaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("GunplaId");

                    b.HasIndex("GradeId");

                    b.ToTable("Gunpla");
                });

            modelBuilder.Entity("GunplaridiseSite.Models.Gunpla", b =>
                {
                    b.HasOne("GunplaridiseSite.Models.Grade", "Grade")
                        .WithMany("Gunplas")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("GunplaridiseSite.Models.Grade", b =>
                {
                    b.Navigation("Gunplas");
                });
#pragma warning restore 612, 618
        }
    }
}
